//shift + alt + f acomoda el array para que quede separado y legible.

export const personas = [
  {
    id: 1,
    first_name: "Olenolin",
    last_name: "Duckering",
    email: "oduckering0@adobe.com",
    gender: "Male",
  },
  {
    id: 2,
    first_name: "Rebbecca",
    last_name: "Von Brook",
    email: "rvonbrook1@fastcompany.com",
    gender: "Female",
  },
  {
    id: 3,
    first_name: "Alidia",
    last_name: "Trimme",
    email: "atrimme2@hibu.com",
    gender: "Female",
  },
  {
    id: 4,
    first_name: "Hersch",
    last_name: "Cluderay",
    email: "hcluderay3@ifeng.com",
    gender: "Male",
  },
  {
    id: 5,
    first_name: "Carlye",
    last_name: "Colclough",
    email: "ccolclough4@businessweek.com",
    gender: "Female",
  },
  {
    id: 6,
    first_name: "Reynolds",
    last_name: "Stiffell",
    email: "rstiffell5@jugem.jp",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Shannen",
    last_name: "Presley",
    email: "spresley6@newyorker.com",
    gender: "Female",
  },
  {
    id: 8,
    first_name: "Henrik",
    last_name: "Almak",
    email: "halmak7@time.com",
    gender: "Male",
  },
  {
    id: 9,
    first_name: "Nathanil",
    last_name: "Storrock",
    email: "nstorrock8@google.nl",
    gender: "Male",
  },
  {
    id: 10,
    first_name: "Melamie",
    last_name: "Michelet",
    email: "mmichelet9@hostgator.com",
    gender: "Female",
  },
  {
    id: 11,
    first_name: "Avigdor",
    last_name: "Teal",
    email: "ateala@sciencedirect.com",
    gender: "Male",
  },
  {
    id: 12,
    first_name: "Ronnie",
    last_name: "Varfolomeev",
    email: "rvarfolomeevb@cbc.ca",
    gender: "Male",
  },
  {
    id: 13,
    first_name: "Coralie",
    last_name: "Benez",
    email: "cbenezc@de.vu",
    gender: "Genderfluid",
  },
  {
    id: 14,
    first_name: "Lewie",
    last_name: "Melbert",
    email: "lmelbertd@huffingtonpost.com",
    gender: "Male",
  },
  {
    id: 15,
    first_name: "Kandy",
    last_name: "O'Luby",
    email: "kolubye@godaddy.com",
    gender: "Female",
  },
  {
    id: 16,
    first_name: "Ynes",
    last_name: "Cave",
    email: "ycavef@tinypic.com",
    gender: "Female",
  },
  {
    id: 17,
    first_name: "Marven",
    last_name: "Bru",
    email: "mbrug@wired.com",
    gender: "Male",
  },
  {
    id: 18,
    first_name: "Rhett",
    last_name: "Andriolli",
    email: "randriollih@youku.com",
    gender: "Male",
  },
  {
    id: 19,
    first_name: "Papageno",
    last_name: "Boeck",
    email: "pboecki@freewebs.com",
    gender: "Non-binary",
  },
  {
    id: 20,
    first_name: "Tyler",
    last_name: "Whittam",
    email: "twhittamj@constantcontact.com",
    gender: "Male",
  },
  {
    id: 21,
    first_name: "Haze",
    last_name: "Davidy",
    email: "hdavidyk@shareasale.com",
    gender: "Male",
  },
  {
    id: 22,
    first_name: "Aristotle",
    last_name: "McElvogue",
    email: "amcelvoguel@biblegateway.com",
    gender: "Male",
  },
  {
    id: 23,
    first_name: "Alvie",
    last_name: "Dytham",
    email: "adythamm@taobao.com",
    gender: "Male",
  },
  {
    id: 24,
    first_name: "Dalli",
    last_name: "Mattea",
    email: "dmattean@bravesites.com",
    gender: "Male",
  },
  {
    id: 25,
    first_name: "Elonore",
    last_name: "Battison",
    email: "ebattisono@desdev.cn",
    gender: "Female",
  },
  {
    id: 26,
    first_name: "Berny",
    last_name: "Jovic",
    email: "bjovicp@un.org",
    gender: "Male",
  },
  {
    id: 27,
    first_name: "Tommy",
    last_name: "Scheu",
    email: "tscheuq@ihg.com",
    gender: "Male",
  },
  {
    id: 28,
    first_name: "Shadow",
    last_name: "Biasini",
    email: "sbiasinir@blogs.com",
    gender: "Male",
  },
  {
    id: 29,
    first_name: "Modesty",
    last_name: "Pavia",
    email: "mpavias@youtu.be",
    gender: "Female",
  },
  {
    id: 30,
    first_name: "Baily",
    last_name: "Fritz",
    email: "bfritzt@51.la",
    gender: "Male",
  },
  {
    id: 31,
    first_name: "Glynis",
    last_name: "Erington",
    email: "geringtonu@com.com",
    gender: "Female",
  },
  {
    id: 32,
    first_name: "Kane",
    last_name: "Maclean",
    email: "kmacleanv@altervista.org",
    gender: "Male",
  },
  {
    id: 33,
    first_name: "Madison",
    last_name: "Gehrels",
    email: "mgehrelsw@webeden.co.uk",
    gender: "Male",
  },
  {
    id: 34,
    first_name: "Josy",
    last_name: "Freed",
    email: "jfreedx@scribd.com",
    gender: "Female",
  },
  {
    id: 35,
    first_name: "Delila",
    last_name: "Ebbrell",
    email: "debbrelly@e-recht24.de",
    gender: "Female",
  },
  {
    id: 36,
    first_name: "Jannel",
    last_name: "Gopsill",
    email: "jgopsillz@ezinearticles.com",
    gender: "Female",
  },
  {
    id: 37,
    first_name: "Glennie",
    last_name: "Yurevich",
    email: "gyurevich10@multiply.com",
    gender: "Female",
  },
  {
    id: 38,
    first_name: "Aurel",
    last_name: "Blowing",
    email: "ablowing11@reverbnation.com",
    gender: "Female",
  },
  {
    id: 39,
    first_name: "Reggie",
    last_name: "Crafts",
    email: "rcrafts12@squarespace.com",
    gender: "Female",
  },
  {
    id: 40,
    first_name: "Faber",
    last_name: "Smith",
    email: "fsmith13@ed.gov",
    gender: "Male",
  },
  {
    id: 41,
    first_name: "Georgena",
    last_name: "Eggers",
    email: "geggers14@thetimes.co.uk",
    gender: "Female",
  },
  {
    id: 42,
    first_name: "Alan",
    last_name: "Gagan",
    email: "agagan15@howstuffworks.com",
    gender: "Male",
  },
  {
    id: 43,
    first_name: "Morris",
    last_name: "Crombleholme",
    email: "mcrombleholme16@washingtonpost.com",
    gender: "Male",
  },
  {
    id: 44,
    first_name: "Carolee",
    last_name: "Battrum",
    email: "cbattrum17@devhub.com",
    gender: "Female",
  },
  {
    id: 45,
    first_name: "Ali",
    last_name: "Loudon",
    email: "aloudon18@ox.ac.uk",
    gender: "Male",
  },
  {
    id: 46,
    first_name: "Isidore",
    last_name: "Ludford",
    email: "iludford19@qq.com",
    gender: "Male",
  },
  {
    id: 47,
    first_name: "Krysta",
    last_name: "Ledster",
    email: "kledster1a@blogspot.com",
    gender: "Female",
  },
  {
    id: 48,
    first_name: "Ethel",
    last_name: "Primmer",
    email: "eprimmer1b@parallels.com",
    gender: "Genderqueer",
  },
  {
    id: 49,
    first_name: "Westley",
    last_name: "Cess",
    email: "wcess1c@usgs.gov",
    gender: "Male",
  },
  {
    id: 50,
    first_name: "Tobey",
    last_name: "Francesch",
    email: "tfrancesch1d@blogtalkradio.com",
    gender: "Female",
  },
];
