export const personas = [
  {
    id: 1,
    nombre: "Dan",
    edad: 27,
    genero: "M",
    sueldo: 1382.54,
    pais: "China",
  },
  {
    id: 2,
    nombre: "Cullan",
    edad: 29,
    genero: "M",
    sueldo: 1411.94,
    pais: "Croatia",
  },
  {
    id: 3,
    nombre: "Tamqrah",
    edad: 22,
    genero: "F",
    sueldo: 1244.58,
    pais: "Bonaire, Saint Eustatius and Saba ",
  },
  {
    id: 4,
    nombre: "Blythe",
    edad: 26,
    genero: "F",
    sueldo: 1704.31,
    pais: "Indonesia",
  },
  {
    id: 5,
    nombre: "Craig",
    edad: 20,
    genero: "M",
    sueldo: 1938.36,
    pais: "Czech Republic",
  },
  {
    id: 6,
    nombre: "Marcille",
    edad: 20,
    genero: "F",
    sueldo: 1472.99,
    pais: "Indonesia",
  },
  {
    id: 7,
    nombre: "Yanaton",
    edad: 21,
    genero: "M",
    sueldo: 1777.93,
    pais: "Brazil",
  },
  {
    id: 8,
    nombre: "Analiese",
    edad: 36,
    genero: "F",
    sueldo: 1529.58,
    pais: "Macedonia",
  },
  {
    id: 9,
    nombre: "Bowie",
    edad: 34,
    genero: "M",
    sueldo: 1750.12,
    pais: "China",
  },
  {
    id: 10,
    nombre: "Hortensia",
    edad: 32,
    genero: "F",
    sueldo: 1789.77,
    pais: "Russia",
  },
  {
    id: 11,
    nombre: "Costa",
    edad: 53,
    genero: "M",
    sueldo: 1057.87,
    pais: "Tanzania",
  },
  {
    id: 12,
    nombre: "Berton",
    edad: 46,
    genero: "M",
    sueldo: 1409.86,
    pais: "Indonesia",
  },
  {
    id: 13,
    nombre: "Merle",
    edad: 35,
    genero: "F",
    sueldo: 1590.26,
    pais: "China",
  },
  {
    id: 14,
    nombre: "Sallee",
    edad: 37,
    genero: "F",
    sueldo: 1554.33,
    pais: "Portugal",
  },
  {
    id: 15,
    nombre: "Stephen",
    edad: 25,
    genero: "M",
    sueldo: 1286.05,
    pais: "Angola",
  },
  {
    id: 16,
    nombre: "Randi",
    edad: 57,
    genero: "M",
    sueldo: 1192.05,
    pais: "Indonesia",
  },
  {
    id: 17,
    nombre: "Bernadene",
    edad: 50,
    genero: "F",
    sueldo: 1589.87,
    pais: "Indonesia",
  },
  {
    id: 18,
    nombre: "Cosmo",
    edad: 33,
    genero: "M",
    sueldo: 1769.67,
    pais: "Portugal",
  },
  {
    id: 19,
    nombre: "Melamie",
    edad: 47,
    genero: "F",
    sueldo: 1278.49,
    pais: "Russia",
  },
  {
    id: 20,
    nombre: "Kalle",
    edad: 30,
    genero: "M",
    sueldo: 1994.25,
    pais: "Indonesia",
  },
  {
    id: 21,
    nombre: "Osborne",
    edad: 20,
    genero: "M",
    sueldo: 1801.74,
    pais: "Kyrgyzstan",
  },
  {
    id: 22,
    nombre: "Bert",
    edad: 45,
    genero: "M",
    sueldo: 1748.34,
    pais: "Sweden",
  },
  {
    id: 23,
    nombre: "Waverly",
    edad: 31,
    genero: "M",
    sueldo: 1068.88,
    pais: "Ukraine",
  },
  {
    id: 24,
    nombre: "Sheffy",
    edad: 21,
    genero: "M",
    sueldo: 1253.83,
    pais: "Malaysia",
  },
  {
    id: 25,
    nombre: "Murial",
    edad: 28,
    genero: "F",
    sueldo: 1198.37,
    pais: "Sweden",
  },
  {
    id: 26,
    nombre: "Meir",
    edad: 62,
    genero: "M",
    sueldo: 1001.59,
    pais: "Russia",
  },
  {
    id: 27,
    nombre: "Onfroi",
    edad: 33,
    genero: "M",
    sueldo: 1924.69,
    pais: "China",
  },
  {
    id: 28,
    nombre: "Ruthie",
    edad: 37,
    genero: "F",
    sueldo: 1666.07,
    pais: "Mexico",
  },
  {
    id: 29,
    nombre: "Cyrille",
    edad: 20,
    genero: "M",
    sueldo: 1934.69,
    pais: "Vietnam",
  },
  {
    id: 30,
    nombre: "Tobias",
    edad: 65,
    genero: "M",
    sueldo: 1944.94,
    pais: "Argentina",
  },
  {
    id: 31,
    nombre: "Eleanore",
    edad: 31,
    genero: "F",
    sueldo: 1438.65,
    pais: "Russia",
  },
  {
    id: 32,
    nombre: "Doralyn",
    edad: 27,
    genero: "F",
    sueldo: 1822.99,
    pais: "Russia",
  },
  {
    id: 33,
    nombre: "Klarrisa",
    edad: 33,
    genero: "F",
    sueldo: 1766.75,
    pais: "Japan",
  },
  {
    id: 34,
    nombre: "Rosabel",
    edad: 48,
    genero: "F",
    sueldo: 1607.97,
    pais: "China",
  },
  {
    id: 35,
    nombre: "Ermanno",
    edad: 50,
    genero: "M",
    sueldo: 1654.5,
    pais: "China",
  },
  {
    id: 36,
    nombre: "Mallory",
    edad: 54,
    genero: "F",
    sueldo: 1667.96,
    pais: "Philippines",
  },
  {
    id: 37,
    nombre: "Jere",
    edad: 20,
    genero: "M",
    sueldo: 1578.14,
    pais: "New Zealand",
  },
  {
    id: 38,
    nombre: "Dael",
    edad: 41,
    genero: "F",
    sueldo: 1956.04,
    pais: "China",
  },
  {
    id: 39,
    nombre: "Ansley",
    edad: 44,
    genero: "F",
    sueldo: 1250.5,
    pais: "China",
  },
  {
    id: 40,
    nombre: "Barbara",
    edad: 24,
    genero: "F",
    sueldo: 1873.55,
    pais: "Mongolia",
  },
  {
    id: 41,
    nombre: "Faun",
    edad: 58,
    genero: "F",
    sueldo: 1437.35,
    pais: "Russia",
  },
  {
    id: 42,
    nombre: "Ardith",
    edad: 39,
    genero: "F",
    sueldo: 1138.7,
    pais: "Madagascar",
  },
  {
    id: 43,
    nombre: "Gail",
    edad: 37,
    genero: "F",
    sueldo: 1056.03,
    pais: "Indonesia",
  },
  {
    id: 44,
    nombre: "Reinwald",
    edad: 24,
    genero: "M",
    sueldo: 1093.1,
    pais: "Montenegro",
  },
  {
    id: 45,
    nombre: "Sandor",
    edad: 49,
    genero: "M",
    sueldo: 1178.48,
    pais: "China",
  },
  {
    id: 46,
    nombre: "Lek",
    edad: 30,
    genero: "M",
    sueldo: 1275.47,
    pais: "China",
  },
  {
    id: 47,
    nombre: "Ky",
    edad: 36,
    genero: "M",
    sueldo: 1306.59,
    pais: "Indonesia",
  },
  {
    id: 48,
    nombre: "Herbert",
    edad: 32,
    genero: "M",
    sueldo: 1686.94,
    pais: "Brazil",
  },
  {
    id: 49,
    nombre: "Luke",
    edad: 44,
    genero: "M",
    sueldo: 1291.01,
    pais: "Indonesia",
  },
  {
    id: 50,
    nombre: "Marwin",
    edad: 19,
    genero: "M",
    sueldo: 1978.38,
    pais: "Vietnam",
  },
];
